### ISSUE TITLE
Invalid reference to senseui-widgetlibrary/Drill-KPI.json 

### ISSUE THREAD

**Issue by mountaindude** [yianni-ververis/SenseUI-WidgetLibrary#1]
After adding the senseui-widgetlibrary to a Sense 3.0.1 Enterprise environment, there is an error in the Chrome Dev Tools whenever I open an app sheet in edit mode:

Request URL:https://<myURL>/dev/extensions/senseui-widgetlibrary/Drill-KPI.json?1475914052516&xrfkey=MmewGGsSNKTqOM1t
Request Method:GET
Status Code:404 Not Found

The drill KPI is part of the widget sample library that ships with Sense I believe... but that file is still references from the senseui-widgetlibrary?

Copy-paste error?

**Comment by vehid** [comment]
The way i solved this issue is, i downloaded the senseui-widgetlibrary,and extracted it and also extracted the other zip file inside called 'senseui-widgetlibrary.zip' ,inside was Drill-KPI.html and Drill-KPI.json.I've copied everything from folder ,and paste it inside  'C:\ProgramData\Qlik\Sense\Repository\Extensions\senseui-widgetlibrary'.
![first image](https://cloud.githubusercontent.com/assets/25608967/22688456/a7ab3160-ed2c-11e6-914c-a87e7193a306.png)
Also i have zipped this folder 'senseui-widgetlibrary' 
and import it inside /qmc/extensions,refreshed application and now it doesn't show that error.And if there is imported  'senseui-widgetlibrary'  in qmc,delete that first,then import new.

**Comment by yianni-ververis** [comment]
Hello Vehid,

I've just added the files into the repo. If you want to remove them, from .qext file, remove the reference at L9
